### Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: roboshop
  ## deployment labels
  labels:
    component: frontend
    project: roboshop
    tier: web
spec:
  replicas: 1
  ## these are the labels replica set use to create pod replicas, this should match pod labels
  selector:
    matchLabels:
      component: frontend
      project: roboshop
      tier: web
  ## This is pod definition
  template:
    metadata:
      labels:
        component: frontend
        project: roboshop
        tier: web
    spec:
      containers:
      - name: frontend
        image: mohanvamsi011/frontend:v1
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "100m"
            memory: "256Mi"

---
### Service
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: roboshop
  labels:
    component: frontend
    project: roboshop
    tier: web
spec:
  type: LoadBalancer
  selector:
    component: frontend
    project: roboshop
    tier: web
  ports:
    - protocol: TCP 
      port: 80  ## service port
      targetPort: 80  ## container port

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend
  namespace: roboshop
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 10