### ConfigMap
apiVersion: v1
kind: ConfigMap
metadata: 
  name: cart
  namespace: roboshop
  labels:
    component: cart
    project: roboshop
    tier: app
data:
  REDIS_HOST: "redis" 
  CATALOGUE_HOST: "catalogue" 
  CATALOGUE_PORT: "8080"

---
### Deployment
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: cart
  namespace: roboshop
  labels:
    component: cart
    project: roboshop
    tier: app
spec:
  selector:
    matchLabels:
      component: cart
      project: roboshop
      tier: app
  replicas: 2
  ### This is Pod definiton
  template:
    metadata:
      name: cart
      labels:
        component: cart
        project: roboshop
        tier: app
    spec:
      containers:
      - name: cart
        image: mohanvamsi011/cart:v1
        envFrom:
        - configMapRef:
            name: cart
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 256Mi

---
### cart Service
apiVersion: v1
kind: Service
metadata: 
  name: cart
  namespace: roboshop
  labels:
    component: cart
    project: roboshop
    tier: app
spec:
  selector:
    component: cart
    project: roboshop
    tier: app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
      
---
### Autoscaling
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cart
  namespace: roboshop
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cart
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource: 
      name: cpu
      target:
        type: Utilization
        averageUtilization: 10
