### ConfigMap
apiVersion: v1
kind: ConfigMap
metadata: 
  name: shipping
  namespace: roboshop
  labels:
    component: shipping
    project: roboshop
    tier: app
data:
  CART_ENDPOINT: "cart:8080" 
  DB_HOST: "mysql"
  
---
### Deployment
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
  labels:
    component: shipping
    project: roboshop
    tier: app
spec:
  selector:
    matchLabels:
      component: shipping
      project: roboshop
      tier: app
  replicas: 2
  ### This is Pod definiton
  template:
    metadata:
      name: shipping
      labels:
        component: shipping
        project: roboshop
        tier: app
    spec:
      containers:
      - name: shipping
        image: mohanvamsi011/shipping:v1
        envFrom:
        - configMapRef:
            name: shipping
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 512Mi

---
### shipping Service
apiVersion: v1
kind: Service
metadata: 
  name: shipping
  namespace: roboshop
  labels:
    component: shipping
    project: roboshop
    tier: app
spec:
  selector:
    component: shipping
    project: roboshop
    tier: app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
      
---
### Autoscaling
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: shipping
  namespace: roboshop
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shipping
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource: 
      name: cpu
      target:
        type: Utilization
        averageUtilization: 10
