apiVersion: v1
kind: Secret
metadata:
  name: mysql
  namespace: roboshop
  labels:
    component: mysql
    project: roboshop
    tier: database
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: Um9ib1Nob3BAMQ==

---
### headless service
apiVersion: v1
kind: Service
metadata: 
  name: mysql-headless
  namespace: roboshop
  labels:
    component: mysql
    project: roboshop
    tier: database
spec:
  clusterIP: None
  selector:
    component: mysql
    project: roboshop
    tier: database
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306

---
### mysql service
apiVersion: v1
kind: Service
metadata:   
  name: mysql
  namespace: roboshop
  labels:
    component: mysql
    project: roboshop
    tier: database
spec:
  selector:
    component: mysql
    project: roboshop
    tier: database
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306

---
### StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: roboshop
  labels:
    component: mysql
    project: roboshop
    tier: database
spec:
  selector:
    matchLabels:
      component: mysql
      project: roboshop
      tier: database
  serviceName: mysql-headless
  replicas: 2
  ### his is pod definition
  template:
    metadata:
      name: mysql
      labels:
        component: mysql
        project: roboshop
        tier: database
  spec:
    containers:
    - name: mysql 
      image: mohanvamsi011/mysql:v1
      volumeMounts:
      - name: mysql-data
        mountPath: /var/lib/mysql
  ### This is pVC definition
  volumeClaimTemplates:
  - metadata:
    name: mysql-data 
  spec:
    accessModes:
    - ReadWriteOnce
    storageClassName: ebs-roboshop
    resources:
      requests:
        storage: 2Gi
