### ConfigMap
apiVersion: v1
kind: ConfigMap
metadata: 
  name: catalogue
  namespace: roboshop
  labels:
    component: catalogue
    project: roboshop
    tier: app
data:
  MONGO: "true"
  MONGO_URL: "mongodb://mongodb:27017/catalogue"

---
### Deployment
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    component: catalogue
    project: roboshop
    tier: app
spec:
  selector:
    matchLabels:
      component: catalogue
      project: roboshop
      tier: app
  replicas: 2
  ### This is Pod definiton
  template:
    metadata:
      name: catalogue
      labels:
        component: catalogue
        project: roboshop
        tier: app
    spec:
      containers:
      - name: catalogue
        image: mohanvamsi011/catalogue:v1
        envFrom:
        - configMapRef:
            name: catalogue
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 256Mi

---
### Catalogue Service
apiVersion: v1
kind: Service
metadata: 
  name: catalogue
  namespace: roboshop
  labels:
    component: catalogue
    project: roboshop
    tier: app
spec:
  selector:
    component: catalogue
    project: roboshop
    tier: app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
      
---
### Autoscaling
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: catalogue
  namespace: roboshop
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: catalogue
    minReplicas: 1
    maxReplicas: 10
    metrics:
    - type: Resource
      resource: 
        name: cpu
        target:
          type: Utilization
          averageUtilization: 10
