### ConfigMap
apiVersion: v1
kind: ConfigMap
metadata: 
  name: user
  namespace: roboshop
  labels:
    component: user
    project: roboshop
    tier: app
data:
  MONGO: "true" 
  MONGO_URL: "mongodb://mongodb:27017/users" 
  REDIS_URL: "redis://redis:6379"

---
### Deployment
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: user
  namespace: roboshop
  labels:
    component: user
    project: roboshop
    tier: app
spec:
  selector:
    matchLabels:
      component: user
      project: roboshop
      tier: app
  replicas: 2
  ### This is Pod definiton
  template:
    metadata:
      name: user
      labels:
        component: user
        project: roboshop
        tier: app
    spec:
      containers:
      - name: user
        image: mohanvamsi011/user:v1
        envFrom:
        - configMapRef:
            name: user
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 256Mi

---
### user Service
apiVersion: v1
kind: Service
metadata: 
  name: user
  namespace: roboshop
  labels:
    component: user
    project: roboshop
    tier: app
spec:
  selector:
    component: user
    project: roboshop
    tier: app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
      
---
### Autoscaling
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: user
  namespace: roboshop
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource: 
      name: cpu
      target:
        type: Utilization
        averageUtilization: 10
