### headless service
apiVersion: v1
kind: Service
metadata: 
  name: redis-headless
  namespace: roboshop
  labels:
    component: mongodb
    project: roboshop
    tier: database
spec:
  clusterIP: None
  selector:
    labels:
    component: mongodb
    project: roboshop
    tier: database
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379